logging:
  sinks:
    stackdriver:
      resource_type: global
  loggers:
    my_application_logs:
      resource_type: project
      sinks:
        - stackdriver
      includes:
        - /var/log/nodeapplication/*.log
