name: CI Compile check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display .env file
        run: |
          echo "DB_DIALECT=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=Pramsai@123" >> .env
          echo "DB_NAME=health_check_db" >> .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Pramsai@123'; FLUSH PRIVILEGES;"
          mysql -u root -p'Pramsai@123' -e "CREATE DATABASE IF NOT EXISTS health_check_db;"

      - name: Run Tests
        run: npm test
