name: CI Compile check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display .env file
        run: |
          echo "DB_DIALECT=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=Pramsai@123" >> .env
          echo "DB_NAME=health_check_db" >> .env

      - name: Configure MySQL
        run: |
          npm install mysql
          node -e "const mysql = require('mysql'); const connection = mysql.createConnection({ host: 'localhost', user: 'root', password: 'Pramsai@123' }); connection.connect(function(err) { if (err) throw err; connection.query('CREATE DATABASE IF NOT EXISTS health_check_db', function (err, result) { if (err) throw err; console.log('Database created or already exists'); }); });"

      - name: Run Tests
        run: npm test
