name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: health_check_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      
      - name: Start MySQL Service
        run: sudo service mysql start
      
      - name: Create Database
        run: |
          mysql --host=localhost --port=3306 --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS health_check_db;"
      
      - name: Install Dependencies
        run: npm install
      
      - name: Start Application Server
        run: node HealthCheckServer.js &
    
      - name: Wait for Server to Start
        run: sleep 10
      
      - name: Run Integration Tests
        run: npm test
