name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server

    - name: Start MySQL service
      run: sudo service mysql start

    - name: Setup MySQL database
      run: |
        mysql -u root -e "CREATE DATABASE health_check_db;"
        mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'Pramsai@123';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON health_check_db.* TO 'root'@'localhost';"

    - name: Set up environment variables
      run: |
        echo "DB_DIALECT=mysql" >> $GITHUB_ENV
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "DB_USERNAME=root" >> $GITHUB_ENV
        echo "DB_PASSWORD=Pramsai@123" >> $GITHUB_ENV
        echo "DB_NAME=health_check_db" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
