name: CI Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client
      
      - name: Install Jest
        run: npm install --save-dev jest
      
      - name: Install supertest
        run: npm install --save-dev supertest


      - name: Display .env file
        run: |
          echo "DB_DIALECT=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=Pramsai@123" >> .env
          echo "DB_NAME=health_check_db" >> .env

      - name: Configure MySQL and create database
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS health_check_db;"
          sudo mysql --user=root --password=root -e "SHOW DATABASES;"

      - name: Run integration tests
        run: npm test
