name: CI Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set NODE_ENV to development
        run: export NODE_ENV=development

      - name: Create MySQL User
        run: |
          sudo mysql -u root -pPramsai@123 -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'Pramsai@123';"

      - name: Create MySQL Database
        run: |
          sudo mysql -u root -pPramsai@123 -e "CREATE DATABASE IF NOT EXISTS health_check_db;"

      - name: Grant Privileges to MySQL User
        run: |
          sudo mysql -u root -pPramsai@123 -e "GRANT ALL PRIVILEGES ON health_check_db.* TO 'root'@'localhost';"

      - name: Run Integration Tests
        run: npm test || exit 1
