name: CI Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Start MySQL server
        run: sudo systemctl start mysql

      - name: Check MySQL server status
        run: sudo systemctl status mysql

      - name: Connect to MySQL server and create database
        run: |
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS health_check_db;"

      - name: Run integration tests
        run: npm test
