name: CI Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set NODE_ENV to development
        run: export NODE_ENV=development

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -h 127.0.0.1 --port 3306 -uroot -PPramsai@123 -e "CREATE DATABASE IF NOT EXISTS health_check_db"
     

      - name: Run integration tests
        run: npm test 
