name: Packer Template Checks

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Initialize Packer
        run: packer init webapp-packer.pkr.hcl

      - name: Validate Packer Template
        run: packer validate webapp-packer.pkr.hcl

      