name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer_validation:
    name: Packer Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Initialize Packer project
        run: packer init webapp-packer.pkr.hcl


      - name: Format Packer template
        run: packer fmt -check webapp-packer.pkr.hcl

      - name: Validate Packer template
        run: packer validate webapp-packer.pkr.hcl

      

