name: Packer Workflow

on: [pull_request]

jobs:
  packer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
        unzip packer_1.7.3_linux_amd64.zip
        chmod +x packer
        sudo mv packer /usr/local/bin/
    
    - name: Initialize Packer
      run: packer init ../webapp-packer.pkr.hcl
    
    - name: Check Formatting
      run: packer fmt -check ../webapp-packer.pkr.hcl
    
    - name: Validate Packer Template
      run: packer validate  ../webapp-packer.pkr.hcl
