name: Packer format and validate

on:
  pull_request:
    branches: [main]  # Trigger only for pull requests to the main branch

jobs:
  packer-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-packer@v1

      - name: Run packer fmt
        run: packer fmt -check .

      - name: Fail if packer fmt modified files
        run: |
          if git diff --exit-code --quiet; then
            echo "packer fmt did not modify any files"
          else
            echo "packer fmt modified files, please commit the changes and push again"
            exit 1
          fi

      - name: Run packer validate
        run: packer validate .

      - name: Fail if packer validate failed
        run: |
          if [[ $? -eq 0 ]]; then
            echo "packer validate successful"
          else
            echo "packer validate failed, please fix the template"
            exit 1
          fi
