name: Packer Template Checks

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application artifact
        run: zip -r application.zip ./*

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Initialize Packer
        run: packer init webapp-application.pkr.hcl


      - name: Validate Packer Template
        run: |
          packer validate webapp-application.pkr.hcl
          packer fmt webapp-application.pkr.hcl

      - name: Format Packer Template
        run: |
          if ! packer fmt -check -diff webapp-application.pkr.hcl; then
            echo "Packer template is not properly formatted. Please run 'packer fmt' to format the template."
            exit 1
          fi

      