name: Packer Validation and Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_validation_and_format_check:
    name: Packer Validation and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Validate Packer template
        run: |
          if ! packer validate webapp-packer.pkr.hcl; then
            echo "Packer template validation failed."
            exit 1
          fi

      - name: Check Packer format
        run: |
          if ! packer fmt -check; then
            echo "Packer format check failed. Please run 'packer fmt' to fix formatting issues."
            exit 1
          fi
