name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip -o packer.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: Format Packer Template
        run: packer fmt webapp-packer.pkr.hcl


      - name: Validate Packer Template
        run: packer validate webapp-packer.pkr.hcl
